channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - click=8.1.3
  - ipykernel=6.22.0
  - ipython=8.11.0
  - ipywidgets=8.0.5
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_nbextensions_configurator=0.6.1
  - matplotlib=3.7.1
  - numpy=1.24.2
  - pandas=1.5.3
  - pip=23.0.1
  - python=3.8.8
  - pytorch=2.0.0
  - scikit-learn=1.2.2
  - seaborn=0.12.2
  - torchvision=0.15.0
